/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type Circle = {
  radius: number;
  x: number;
  y: number;
};

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Point = {
  x: number;
  y: number;
};

export type TestEnumTypeVarchar = "test 1" | "test 2" | "test 3";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Change {
  action: string;
  change_request_id: string;
  connection_id: string;
  id: Generated<string>;
  index: number;
  metadata_database_name: string;
  metadata_schema_name: string;
  metadata_table_name: string;
}

export interface ChangeFieldValue {
  binary_value: Buffer | null;
  boolean_value: boolean | null;
  change_id: string;
  column_name: string;
  date_value: Timestamp | null;
  id: Generated<string>;
  is_value_null: boolean;
  json_value: Json | null;
  numeric_value: Numeric | null;
  string_value: string | null;
  uuid_value: string | null;
}

export interface ChangePreviousFieldValue {
  binary_value: Buffer | null;
  boolean_value: boolean | null;
  change_id: string;
  column_name: string;
  date_value: Timestamp | null;
  id: Generated<string>;
  is_value_null: boolean;
  json_value: Json | null;
  numeric_value: Numeric | null;
  string_value: string | null;
  uuid_value: string | null;
}

export interface ChangePreviousPrimaryKey {
  binary_value: Buffer | null;
  boolean_value: boolean | null;
  change_id: string;
  column_name: string;
  date_value: Timestamp | null;
  id: Generated<string>;
  json_value: Json | null;
  numeric_value: Numeric | null;
  string_value: string | null;
  uuid_value: string | null;
}

export interface ChangePrimaryKey {
  binary_value: Buffer | null;
  boolean_value: boolean | null;
  change_id: string;
  column_name: string;
  date_value: Timestamp | null;
  id: Generated<string>;
  json_value: Json | null;
  numeric_value: Numeric | null;
  string_value: string | null;
  uuid_value: string | null;
}

export interface ChangeRequest {
  change_request_number: number;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  id: Generated<string>;
  metadata_database_connection_id: string;
  metadata_database_raw_name: string;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface ChangeRequestActionType {
  action_type: string;
}

export interface ChangeRequestComment {
  change_id: string | null;
  change_request_id: string;
  content: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  review_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ChangeRequestHistory {
  action_details: Json;
  action_type: string;
  change_request_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  user_id: string;
}

export interface ChangeRequestIssue {
  change_request_id: string;
  issue_id: string;
}

export interface ChangeRequestJob {
  change_request_id: string;
  created_at: Generated<Timestamp>;
  end_time: Timestamp | null;
  error_message: string | null;
  id: Generated<string>;
  rows_affected: number | null;
  start_time: Timestamp | null;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface ChangeRequestLabel {
  change_request_id: string;
  label_id: string;
}

export interface ChangeRequestReviewer {
  change_request_id: string;
  user_id: string;
}

export interface Connection {
  connection_string: string;
  created_at: Timestamp;
  created_by: string;
  data_provider: string;
  id: Generated<string>;
  name: string;
  organization_id: string;
  readonly_connection_id: string | null;
  visibility: string;
  warehouse: string | null;
  with_ssl: Generated<boolean>;
}

export interface DefaultLabel {
  color: string;
  description: string | null;
  id: Generated<string>;
  name: string;
}

export interface Issue {
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  id: Generated<string>;
  issue_number: number;
  metadata_database_connection_id: string;
  metadata_database_raw_name: string;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface IssueActionType {
  action_type: string;
}

export interface IssueAssignee {
  issue_id: string;
  user_id: string;
}

export interface IssueComment {
  content: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  issue_id: string;
  updated_at: Generated<Timestamp>;
}

export interface IssueHistory {
  action_details: Json;
  action_type: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  issue_id: string;
  user_id: string;
}

export interface IssueLabel {
  issue_id: string;
  label_id: string;
}

export interface JobStatus {
  status: string;
}

export interface Label {
  color: string;
  description: string | null;
  id: Generated<string>;
  metadata_database_connection_id: string;
  metadata_database_raw_name: string;
  name: string;
}

export interface LoadingFinished {
  success: number;
}

export interface MetadataDatabase {
  connection_id: string;
  description: string | null;
  display_name: string | null;
  link: string | null;
  organization_id: string;
  raw_name: string;
  slug: string;
  summary: string | null;
}

export interface MetadataTable {
  connection_id: string;
  display_name: string | null;
  raw_database_name: string;
  raw_name: string;
  raw_schema_name: string;
  summary: string | null;
}

export interface Organization {
  banner: string | null;
  created_at: Timestamp;
  created_by: string;
  description: string | null;
  discord_webhook_url: string | null;
  id: Generated<string>;
  link: string | null;
  name: string;
  slack_webhook_url: string | null;
  slug: string;
}

export interface OrganizationInvite {
  created_at: Generated<Timestamp>;
  created_by: string;
  email: string;
  id: Generated<string>;
  name: string;
  organization_id: string;
  role_id: Generated<number>;
  status: Generated<string>;
}

export interface OrganizationUser {
  organization_id: string;
  role_id: Generated<number>;
  user_id: string;
}

export interface Query {
  connection_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  database_name: string;
  description: string | null;
  id: Generated<string>;
  intent: Json | null;
  name: string | null;
  sql: string | null;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface QueryType {
  type: string;
}

export interface Review {
  change_request_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  event_type: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  text: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ReviewEventType {
  event_type: string;
}

export interface Role {
  id: Generated<number>;
  name: string;
}

export interface SchemaJob {
  connection_id: string;
  created_at: Generated<Timestamp>;
  end_time: Timestamp | null;
  error_message: string | null;
  id: Generated<string>;
  start_time: Timestamp | null;
  status: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Snapshot {
  connection_id: string;
  creator: string;
  id: Generated<string>;
  status: string;
  timestamp: Timestamp;
}

export interface SnapshotColumn {
  has_default: boolean | null;
  id: Generated<string>;
  is_primary_key: boolean;
  name: string;
  nullable: boolean;
  position: number;
  table_id: string;
  type: string;
}

export interface SnapshotDatabase {
  id: Generated<string>;
  name: string;
  snapshot_id: string;
}

export interface SnapshotSchema {
  database_id: string;
  id: Generated<string>;
  name: string;
}

export interface SnapshotTable {
  id: Generated<string>;
  is_view: Generated<boolean>;
  name: string;
  schema_id: string;
}

export interface TestChangeRequestTest {
  id: Generated<string>;
  test_binary: Buffer | null;
  test_boolean: boolean | null;
  test_date: Timestamp | null;
  test_jsonb: Json | null;
  test_numeric: Numeric | null;
  test_text: string | null;
  test_timestamp: Timestamp | null;
  test_timestamptz: Timestamp | null;
  test_uuid: string | null;
}

export interface TestChangeRequestTestAllPrimaryKeys {
  binary_id: Buffer;
  boolean_id: boolean;
  id: string;
  jsonb_id: Json;
  numeric_id: Numeric;
  timestamp_id: Timestamp;
}

export interface TestChangeRequestTestNoPrimaryKeys {
  not_id: string;
  test_bytea: Buffer;
}

export interface TestChangeRequestTestRequiredUnknownFields {
  id: Generated<string>;
  test_bit: string | null;
  test_bytea: Buffer;
  test_numeric: Numeric | null;
}

export interface TestChangeRequestTestUnsupportedTypes {
  id: Generated<string>;
  test_bit: string | null;
  test_bit_varying: string | null;
  test_boolean_array: boolean[] | null;
  test_box: string | null;
  test_bytea: Buffer | null;
  test_circle: Circle | null;
  test_enum: TestEnumTypeVarchar | null;
  test_inet: string | null;
  test_integer_array: number[] | null;
  test_integer_array_array: number[] | null;
  test_lseg: string | null;
  test_money: string | null;
  test_numeric_array: ArrayType<Numeric> | null;
  test_path: string | null;
  test_point: Point | null;
  test_polygon: string | null;
  test_text_array: string[] | null;
  test_tsquery: string | null;
  test_tsvector: string | null;
  test_varbit: string | null;
  test_xml: string | null;
}

export interface User {
  administrator: Generated<boolean>;
  email: string | null;
  email_verified: Generated<boolean>;
  id: string;
  login_count: Generated<number>;
  name: string | null;
  password_reset_at: Timestamp | null;
  picture: string | null;
  terms_accepted_at: Timestamp | null;
  username: string;
  username_discord: string | null;
}

export interface UserApiKey {
  created_at: Generated<Timestamp>;
  hash: string;
  id: Generated<string>;
  summary: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface DB {
  change: Change;
  change_field_value: ChangeFieldValue;
  change_previous_field_value: ChangePreviousFieldValue;
  change_previous_primary_key: ChangePreviousPrimaryKey;
  change_primary_key: ChangePrimaryKey;
  change_request: ChangeRequest;
  change_request_action_type: ChangeRequestActionType;
  change_request_comment: ChangeRequestComment;
  change_request_history: ChangeRequestHistory;
  change_request_issue: ChangeRequestIssue;
  change_request_job: ChangeRequestJob;
  change_request_label: ChangeRequestLabel;
  change_request_reviewer: ChangeRequestReviewer;
  connection: Connection;
  default_label: DefaultLabel;
  issue: Issue;
  issue_action_type: IssueActionType;
  issue_assignee: IssueAssignee;
  issue_comment: IssueComment;
  issue_history: IssueHistory;
  issue_label: IssueLabel;
  job_status: JobStatus;
  label: Label;
  loading_finished: LoadingFinished;
  metadata_database: MetadataDatabase;
  metadata_table: MetadataTable;
  organization: Organization;
  organization_invite: OrganizationInvite;
  organization_user: OrganizationUser;
  query: Query;
  query_type: QueryType;
  review: Review;
  review_event_type: ReviewEventType;
  role: Role;
  schema_job: SchemaJob;
  snapshot: Snapshot;
  snapshot_column: SnapshotColumn;
  snapshot_database: SnapshotDatabase;
  snapshot_schema: SnapshotSchema;
  snapshot_table: SnapshotTable;
  "test.change_request_test": TestChangeRequestTest;
  "test.change_request_test_all_primary_keys": TestChangeRequestTestAllPrimaryKeys;
  "test.change_request_test_no_primary_keys": TestChangeRequestTestNoPrimaryKeys;
  "test.change_request_test_required_unknown_fields": TestChangeRequestTestRequiredUnknownFields;
  "test.change_request_test_unsupported_types": TestChangeRequestTestUnsupportedTypes;
  user: User;
  user_api_key: UserApiKey;
}
