/**
 * Use this file to override the types generated by Kysely.
 */

import { Type } from '@sinclair/typebox'

import type {
  DB as GeneratedDB,
  Snapshot as GeneratedSnapshot,
  Connection as GeneratedConnection,
  Query as GeneratedQuery,
  Role as GeneratedRole,
  OrganizationInvite as GeneratedOrganizationInvite,
  Issue as GeneratedIssue,
  ChangeRequest as GeneratedChangeRequest,
  Change as GeneratedChange,
  Review as GeneratedReview,
  JobStatus as GeneratedJobStatus,
  SchemaJob as GeneratedSchemaJob
} from './__generated/kysely.type'
import type { ConnectionDataProvider } from '../schemas/data-provider.schema'
import type { IntentQuery } from '../schemas/query-execution.schema'
import type { Static } from '@sinclair/typebox'
import type { Kysely, ColumnType } from 'kysely'

const SchemaImportStatusSchema = Type.Union(
  (['RUNNING', 'FAILED', 'COMPLETED'] as const).map(n => Type.Literal(n))
)
type SchemaImportStatus = Static<typeof SchemaImportStatusSchema>
interface Snapshot extends Omit<GeneratedSnapshot, 'status' | 'timestamp'> {
  status: SchemaImportStatus
  timestamp: ColumnType<Date, Date | string, Date | string>
}

const RoleNameSchema = Type.Union(
  (['member', 'owner'] as const).map(n => Type.Literal(n))
)
type RoleName = Static<typeof RoleNameSchema>
interface Role extends Omit<GeneratedRole, 'name'> {
  name: RoleName
}

export const VisibilitySchema = Type.Union(
  (['private', 'public'] as const).map(n => Type.Literal(n))
)
export type Visibility = Static<typeof VisibilitySchema>
interface Connection
  extends Omit<GeneratedConnection, 'data_provider' | 'visibility'> {
  data_provider: ConnectionDataProvider
  visibility: Visibility
}

interface Query extends Omit<GeneratedQuery, 'intent' | 'type'> {
  intent: ColumnType<IntentQuery | null, string, string> | null
  type: 'intent' | 'sql'
}

export const OrganizationInviteStatusSchema = Type.Union([
  Type.Literal('accepted'),
  Type.Literal('declined'),
  Type.Literal('pending'),
  Type.Literal('rescinded')
])
type OrganizationInviteStatus = Static<typeof OrganizationInviteStatusSchema>
interface OrganizationInvite
  extends Omit<GeneratedOrganizationInvite, 'status'> {
  status: OrganizationInviteStatus
}

export const IssueStatusSchema = Type.Union(
  (['open', 'closed'] as const).map(n => Type.Literal(n))
)
type IssueStatus = Static<typeof IssueStatusSchema>

export interface Issue extends Omit<GeneratedIssue, 'issue_number' | 'status'> {
  issue_number: ColumnType<number, never, never>
  status: IssueStatus
}

export const ChangeRequestStatusSchema = Type.Union(
  (['open', 'approved', 'executing', 'closed', 'applied'] as const).map(n =>
    Type.Literal(n)
  )
)
export type ChangeRequestStatus = Static<typeof ChangeRequestStatusSchema>

export interface ChangeRequest
  extends Omit<GeneratedChangeRequest, 'change_request_number' | 'status'> {
  change_request_number: ColumnType<number, never, never>
  status: ChangeRequestStatus
}

export const ChangeActionSchema = Type.Union(
  (['ADD', 'MODIFY', 'DELETE'] as const).map(n => Type.Literal(n))
)
export type ChangeAction = Static<typeof ChangeActionSchema>

interface Change extends Omit<GeneratedChange, 'action'> {
  action: ChangeAction
}

export const ReviewEventTypeSchema = Type.Union([
  Type.Literal('APPROVE'),
  Type.Literal('COMMENT')
])
type ReviewEventType = Static<typeof ReviewEventTypeSchema>

export interface Review extends Omit<GeneratedReview, 'event_type'> {
  event_type: ReviewEventType
}

export const JobStatusStatusSchema = Type.Union([
  Type.Literal('PENDING'),
  Type.Literal('RUNNING'),
  Type.Literal('COMPLETED'),
  Type.Literal('FAILED')
])
export type JobStatusStatus = Static<typeof JobStatusStatusSchema>
export interface JobStatus extends Omit<GeneratedJobStatus, 'status'> {
  status: JobStatusStatus
}

export interface SchemaJob extends Omit<GeneratedSchemaJob, 'status'> {
  status: JobStatusStatus
}

// Omit issue and change_request because we have a SQL triggers that generates the issue_number field,
// and Kysely doesn't recognize it.
export interface SortDB
  extends Omit<
    GeneratedDB,
    'issue' | 'change_request' | 'organization_invite' | 'review' | 'snapshot'
  > {
  snapshot: Snapshot
  connection: Connection
  query: Query
  role: Role
  organization_invite: OrganizationInvite
  issue: Issue
  change_request: ChangeRequest
  change: Change
  review: Review
  job_status: JobStatus
  schema_job: SchemaJob
}

export type KyselySortDB = Kysely<SortDB>
