events {}

http {

  map $status $loggable {
    ~^[23]   0; # exclude successful responses
    ~^[404]  0; # exclude 404s
    default  1; # include problems
  }

  access_log /dev/stdout combined if=$loggable;
  error_log /dev/stderr warn;

  upstream sortweb {
    server sort-web:3000;
  }

  server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;

    location / {
      proxy_set_header    X-Forwarded-Host   $host;
      proxy_set_header    X-Forwarded-Server $host;
      proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
      proxy_set_header    X-Forwarded-Proto  $scheme;
      proxy_set_header    X-Real-IP          $remote_addr;
      proxy_set_header    Host               $host;
      proxy_pass http://sortweb;
    }
  }

  server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
  }
}
