# Default values for sort-api-v2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 632392717804.dkr.ecr.us-west-2.amazonaws.com/api
  pullPolicy: IfNotPresent
  tag: c5e6dd6ad8089a433b482d7f0749c0b5886cd3cb

imagePullSecrets: []
nameOverride: "change-request-worker"
fullnameOverride: ""

serviceAccount:
  create: true
  roleArn: "arn:aws:iam::632392717804:role/us-west-2-sort-services-role"
  name: "sort-api-v2"

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

env:
  - name: NODE_ENV
    value: production
  - name: LOG_LEVEL
    value: info
  - name: POSTGRES_HOST
    value: postgres.production.internal.sort.xyz:5432
  - name: POSTGRES_DB
    value: sort_xyz
  - name: POSTGRES_USER
    value: postgres

secretNameRef: "change-request-worker-secrets"

resources:
  # if you move this up, change in the Dockerfile as well
  requests:
    cpu: 400m
    memory: 400Mi
  limits:
    cpu: 600m
    memory: 800Mi

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 10
  failureThreshold: 2
  timeoutSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 20
  failureThreshold: 3
  timeoutSeconds: 5
  terminationGracePeriodSeconds: 45 # more time to finish up customer db transactions

startupProbe:
  httpGet:
    path: /
    port: 8080
  failureThreshold: 10
  periodSeconds: 10
  timeoutSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 81

nodeSelector: {}

tolerations: []

affinity: {}
