/**
 * This script generates a file with all official Postgres error codes and their descriptions.
 * The file is written to src/v2/constants/__generated/postgres.errors.constant.ts
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { parse } from 'node-html-parser'

const url = 'https://www.postgresql.org/docs/13/errcodes-appendix.html'

const generate = async () => {
  const result = await fetch(url)
  const root = parse(await result.text())

  const map = new Map<string, string>()
  const rows = root.querySelectorAll('#ERRCODES-TABLE tbody:first-of-type tr')

  for (const row of rows) {
    const code = row.querySelector('code.literal')?.text
    const desc = row.querySelector('code.symbol')?.text
    if (code && desc) {
      map.set(desc.toLocaleUpperCase(), code)
    }
  }

  const outFile = path.resolve(
    process.cwd(),
    'src',
    'constants',
    '__generated',
    'postgres.errors.constant.ts'
  )

  const src = `/* eslint-disable quotes */
/* eslint-disable prettier/prettier */

// This file is generated by scripts/db/gen-postgres-errors.ts
// Generation date: ${new Date().toISOString()}
// Do not edit this file directly. Instead, run "pnpm db:gen-postgres-errors"
// to regenerate this file.

export const postgresErrorCodes = ${JSON.stringify(
    Object.fromEntries(map),
    null,
    2
  )}
`

  writeFileSync(outFile, src)
  console.log('Generated', outFile)
};

generate();
