name: End-to-End Tests

on:
  push:
    branches:
      - main
  pull_request:
env:
  NODE_ENV: test
  SORT_SESSION_REVOKE_SECRET: ${{ secrets.SORT_SESSION_REVOKE_SECRET }}
  TEST_SNOWFLAKE_HYBRID_CONNECTION_STRING: ${{ secrets.TEST_SNOWFLAKE_HYBRID_CONNECTION_STRING }}
  TEST_SNOWFLAKE_HYBRID_USER: ${{ secrets.TEST_SNOWFLAKE_HYBRID_USER }}
  TEST_SNOWFLAKE_UNLOCK_CONNECTION_STRING: ${{ secrets.TEST_SNOWFLAKE_UNLOCK_CONNECTION_STRING }}
  TEST_POSTGRES_AIR_QUALITY_CONNECTION_STRING: ${{ secrets.TEST_POSTGRES_AIR_QUALITY_CONNECTION_STRING }}

jobs:
  start-e2e-backend:
    name: Start backend
    runs-on: ubuntu-latest-8-core
    outputs:
      test-user-api-key: ${{ steps.create-test-user.outputs.API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'
      - name: install dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: start infra
        run: |
          pnpm run --filter '@sort/shared' infra:up
      - name: create test user
        id: create-test-user
        run: |
          # generate the user
          OUTPUT=$(pnpm run --filter 'sort-api-v2' db:create-test-user)

          # extract the API key
          KEY="$(echo "$OUTPUT" | grep -E 'API key: ' | cut -d':' -f2-)"

          # trim space
          KEY="${KEY#"${KEY%%[![:space:]]*}"}"
          KEY="${KEY%"${KEY##*[![:space:]]}"}"

          echo "API_KEY=$KEY" >> $GITHUB_OUTPUT
      - name: start api
        run: |
          pnpm run --filter 'sort-api-v2' start &
      - name: start worker
        env:
          HEALTH_SERVICE_PORT: 8081
        run: |
          pnpm run --filter '@sort/worker' start &
  test-e2e:
    name: Test end-to-end
    needs: start-e2e-backend
    runs-on: ubuntu-latest-8-core
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      # - name: log sort api and worker processes using netstat
      #   run: |
      #     netstat -tulnp | grep -E "sort-(worker|api)" || echo "No process found"
      # - name: log sort api and worker processes using ps
      #   run: |
      #     ps aux | grep -E "sort-(worker|api)" | grep -v grep || echo "No process found"
      # - name: log sort api and worker processes using lsof
      #   run: |
      #     lsof -i -P -n | grep -E "sort-(api|worker)" || echo "No process found"
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "apps/web/package.json"
      - name: Install @sort/web dependencies
        run: pnpm install
      - name: build @sort/web
        run: pnpm --filter '@sort/web' build
      - name: Install Playwright Browsers
        working-directory: apps/web
        run: pnpm exec playwright install --with-deps ${{ matrix.browser }}
      - name: Run @sort/web e2e tests
        working-directory: apps/web
        run: pnpm exec playwright test --project=${{ matrix.browser }}
        env:
          # required for e2e tests
          SORT_WEB_API_BASE_URL: http://127.0.0.1:8080/
          SORT_WEB_SESSION_SECRET: ${{ secrets.SORT_WEB_SESSION_SECRET }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          TEST_RUN_AI_SUITE: ${{ contains( toJson(github), 'ai-test-suite' ) }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          # required to start the app
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
          SORT_SESSION_REVOKE_SECRET: ${{ secrets.SORT_SESSION_REVOKE_SECRET }}
          SORT_SERVICE_ACCOUNT_API_KEY: ${{ needs.start-e2e-backend.outputs.test-user-api-key }}
          SORT_AUTH: auth0
          # optional app settings
          SORT_WEB_CHANGE_REQUESTS_ENABLED: 1
          SORT_WEB_DESCRIBE_CHANGES_ENABLED: 1
      - name: Upload playwright-report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 14
  stop-e2e-backend:
    name: Stop backend
    needs: test-e2e
    runs-on: ubuntu-latest-8-core
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: stop api
        run: pkill -f "sort-api" || true
      - name: stop worker
        run: pkill -f "sort-worker" || true
      - name: stop infra
        run: |
          pnpm run --filter '@sort/shared' infra:down
