name: Helm Lint

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "helm/**"
      - "kubernetes/**"

jobs:
  api-lint:
    name: Running Helm lint against the chart and values for the API repository
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Helm Lint
        run: |
          ls kubernetes/api/ | grep -v "application.yml" | xargs -I % /bin/bash -c "echo ; echo 'Testing Values and Charts for % Environment'; helm lint helm/api -f kubernetes/api/%/values.yml || exit 255;  sleep 1"

  worker-lint:
    name: Running Helm lint against the chart and values for the worker repository
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Helm Lint
        run: |
          ls kubernetes/worker/ | grep -v "application.yml" | xargs -I % /bin/bash -c "echo ; echo 'Testing Values and Charts for % Environment'; helm lint helm/worker -f kubernetes/worker/%/values.yml || exit 255;  sleep 1"
