name: Build Pipeline

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-development-docker-images:
    if: github.ref == 'refs/heads/develop' && github.actor != 'sortxyz-admin'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download Trivy
        uses: aquasecurity/setup-trivy@v0.2.2 # B/c this download fails often, run first to avoid wasting time building
        with:
          cache: true
          version: v0.56.1

      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SORT_DB_PAT }}

      - name: Update API package version
        working-directory: ./apps/api
        run: |
          npm version patch

      - name: Update worker package version
        working-directory: ./apps/worker
        run: |
          npm version patch

      - name: Configure AWS credentials from Development account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::409563124858:role/OIDC_build_pipeline
          role-session-name: github-actions-ecr
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag development Docker API image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: api
        run: |
          docker build --target api -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:development .

      - name: Run Trivy vulnerability scanner on Docker API image
        uses: aquasecurity/trivy-action@d2a392a13760cb64cb6bbd31d4bed2a7d9a5298d
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/api:${{ github.sha }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Push development Docker API image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: api
        run: |
          echo "Pushing development Docker API image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Build and tag development Docker Worker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: workers
        run: |
          docker build --target worker -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:development .

      - name: Run Trivy vulnerability scanner on Docker Worker image
        uses: aquasecurity/trivy-action@d2a392a13760cb64cb6bbd31d4bed2a7d9a5298d
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/workers:${{ github.sha }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Push development Docker Worker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: workers
        run: |
          echo "Pushing development Worker image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Update Development Values and Push
        run: |
          tag=$(cat ./kubernetes/api/development/values.yml | grep tag: | awk '{print $2}')
          sed -i "s/$tag/$GITHUB_SHA/" ./kubernetes/api/development/values.yml
          tag=$(cat ./kubernetes/worker/development/values.yml | grep tag: | awk '{print $2}')
          sed -i "s/$tag/$GITHUB_SHA/" ./kubernetes/worker/development/values.yml
          git config --global user.name "sortxyz-bot"
          git config --global user.email "sortxyz-bot@users.github.com"
          git commit -am "Update Development Docker images to use $GITHUB_SHA"
          git push

  build-production-docker-images:
    if: github.ref == 'refs/heads/main' && github.actor != 'sortxyz-admin'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download Trivy
        uses: aquasecurity/setup-trivy@v0.2.2 # B/c this download fails often, run first to avoid wasting time building
        with:
          cache: true
          version: v0.56.1

      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SORT_DB_PAT }}

      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::632392717804:role/OIDC_build_pipeline
          role-session-name: github-actions-ecr
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag production Docker API image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: api
        run: |
          docker build --target api -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:production .

      - name: Run Trivy vulnerability scanner on Docker API image
        uses: aquasecurity/trivy-action@d2a392a13760cb64cb6bbd31d4bed2a7d9a5298d
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/api:${{ github.sha }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Push production Docker API image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: api
        run: |
          echo "Pushing production Docker API image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Build and tag production Docker Worker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: workers
        run: |
          docker build --target worker -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:production .

      - name: Run Trivy vulnerability scanner on Docker Worker image
        uses: aquasecurity/trivy-action@d2a392a13760cb64cb6bbd31d4bed2a7d9a5298d
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/workers:${{ github.sha }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Push production Docker Worker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: workers
        run: |
          echo "Pushing production Worker image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Update Production Values and Push
        run: |
          tag=$(cat ./kubernetes/api/production/values.yml | grep tag: | awk '{print $2}')
          sed -i "s/$tag/$GITHUB_SHA/" ./kubernetes/api/production/values.yml
          tag=$(cat ./kubernetes/worker/production/values.yml | grep tag: | awk '{print $2}')
          sed -i "s/$tag/$GITHUB_SHA/" ./kubernetes/worker/production/values.yml
          git config --global user.name "sortxyz-bot"
          git config --global user.email "sortxyz-bot@users.github.com"
          git commit -am "Update Production Docker images to use $GITHUB_SHA"
          git push
